### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by Raraph84** [Arciiix/easy-volume#1]
Hi !
I tried to use this lib on Windows 10 x64 with last updates, but I got an error in code, I found that error with volume.exe
I tried to compile on my computer but same error
![image](https://github.com/Arciiix/easy-volume/assets/52960065/7e8dc140-f789-4046-b3a2-0b05b17ca4d9)
"Unable to run the code because libstdc++-6.dll was not found. Reinstalling the program may correct this problem."

**Comment by Arciiix** [comment]
Hi! Thank you for reaching out! What compiler did you use to compile it? I used GNU C++ compiler (g++ command), shipped with MinGW

**Comment by Raraph84** [comment]
I git cloned the package and ran npm run build ^^

**Comment by Arciiix** [comment]
Okay, I get it. Can you please try to recompile the actual ```volume.exe``` file, by going to ```src/platforms/windows/``` and compiling the native code on your machine using your C++ compiler (e.g. the one I used, GNU C++ compiler shipped with [MinGW](https://www.mingw-w64.org/)), using the command ```g++ main.cpp```, then renaming the file to ```volume.exe``` and copying it into your ```dist``` folder to the relevant path? It seems to be a problem with the compiled executable - that it doesn't work on your setup specifically, that it's missing some DLLs.

Be sure to comment here if you have any problems, I'm here for you 😃 

Have a great day!

**Comment by Raraph84** [comment]
It works now ! Thanks
I have another problem, I open another issue
