### ISSUE TITLE
ERROR in ./node_modules/easy-volume/dist/execCommand.js Module not found: Error: Can't resolve 'child_process'

### ISSUE THREAD

**Issue by abhinavram98** [Arciiix/easy-volume#5]
Hi,

I am trying to use this module in an angular application running in electron. 
I run `npm install easy-volume` and later import it in my TS file with `import { getVolume } from "easy-volume";`

But after trying to build, I get these errors ->

`Error: Module not found: Error: Can't resolve 'child_process' in '/Users/path-to-app/node_modules/easy-volume/dist'`
`Error: Module not found: Error: Can't resolve 'os' in '/Users/path-to-app/node_modules/easy-volume/dist'`

```
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "os": require.resolve("os-browserify/browser") }'
	- install 'os-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "os": false }
```
`Error: Module not found: Error: Can't resolve 'path' in '/Users/abhinavram.ananth/LinkDesktop/RLDC-app/call-popout-app/node_modules/easy-volume/dist/platforms/windows'`
```
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }
```

I tried adding those `resolve` lines to my package.json but I guess I am not adding them using proper syntax.

Anyway to solve these issues?
Thanks

**Comment by Arciiix** [comment]
Hey, thank you so much for using easy-volume!
 
Do you use this library in the renderer process? If so, then it's the cause of the problem - you don't expose the ```child_process``` and ```os``` libraries (which are available on the main process). You can for example try to set the ```nodeIntegration: true``` in webPreferences for mainWindow, but I don't recommend it.

The recommended approach would be to **use easy-volume in your main process and then call the functions via [IPC channels](https://www.electronjs.org/docs/latest/tutorial/ipc)**. This is much safer and will solve many of your additional problems.

Have an amazing day and I'm always here if you need any day!

**Comment by Arciiix** [comment]
If everything works then please tell me, so that I can close the issue

**Comment by abhinavram98** [comment]
Thanks for your quick reply! 
Yes `nodeIntegration` is indeed set to `false` for my project.
Let me quickly try to import it in the main process and report if it works or not.

**Comment by abhinavram98** [comment]
Another question, totally unrelated to this issue, is there any plan to implement like a volume change event? I want to get the current system volume and use it within our application. So it would be nice to have some kind of a channel for "volume-change" that our application can listen to and take appropriate action.

Thanks for your great effort on this module!

**Comment by abhinavram98** [comment]
Hi it seems using `type:commonjs` and using `require` syntax in main.js worked for me. Thanks.

**Comment by Arciiix** [comment]
@abhinavram98 Hey, thank you so much! I'm so happy your issue was solved.
When it comes to your question about future plans, about implementing the volume change event - it seems like a great idea! I'll definitely consider it and do my best to find some time to implement this feature. Thank you so much for the suggestion!
